# global config
global:
  scrape_interval: 15s
  evaluation_interval: 5s

# Scrape configs with multiple scrape targets
scrape_configs:
  - job_name: 'my-fastapi-app'  
    scrape_interval: 5s
    static_configs:
      - targets: ['my-fastapi-app:8000']  

